### ISSUE TITLE
please validdate 

### ISSUE THREAD

**Issue by JeganMurugan01** [Kavinkumars23/apiintegration#5]
`  setTableRows(data.data);` **not validate in app.js** @Kavinkumars23

**Comment by JeganMurugan01** [comment]
useEffect(() => {
    apiService
      .getCustomersData()
      .then((data) => {
        setTableRows(data.data);
      })
      .catch((error) => console.log(error));
  }, []);
  remove the console log and add alert or sweet toast as common and use it here, for throw the  message @Kavinkumars23

**Comment by Kavinkumars23** [comment]
added validation and added sweet alert for error in mentioned place
