### ISSUE TITLE
avoid handleRowClick

### ISSUE THREAD

**Issue by JeganMurugan01** [Kavinkumars23/apiintegration#6]
const navigate = useNavigate();

  function handleRowClick(id) {
    navigate(`/Customer/${id}`);
  }
  const [selectedRadio, setSelectedRadio] = useState({});

  const handleRadioChange = (field, value) => {
    const id = findIdByName(value, field);
    handleRowClick(id);
    setSelectedRadio((prev) => ({ ...prev, [field]: value }));
  };
  
  for single use no need a function 
    **function handleRowClick(id) {
    navigate(`/Customer/${id}`);
  }**
  you can directly call the navigate(`/Customer/${id}`);
  @Kavinkumars23

**Comment by Kavinkumars23** [comment]
removed handleRowClick and used navigate directly
