### ISSUE TITLE
SideBar 

### ISSUE THREAD

**Issue by JeganMurugan01** [Kavinkumars23/apiintegration#8]
const handleAccordionToggle = (index) => {
    setOpenAccordion((prev) => (prev === index ? null : index));
  };
  Here also, your are using function for single use; you can call it directly

**Comment by JeganMurugan01** [comment]
openAccordion === index ? "group-open" : ""
 Check these conditions &&

**Comment by JeganMurugan01** [comment]
<span>{item.title}</span>
please validate here

**Comment by JeganMurugan01** [comment]
<input
                        type="radio"
                        value={item.title === "Name" ? data.name : data.email}
                        checked={
                          selectedRadio[
                            item.title === "Name" ? "name" : "email"
                          ] === (item.title === "Name" ? data.name : data.email)
                        }
                        onChange={(e) =>
                          handleRadioChange(
                            item.title === "Name" ? "name" : "email",
                            e.target.value
                          )
                        }
                      />
                      <label>
                        {item.title === "Name" ? data.name : data.email}
                      </label>
                      please validate **item.title **
                      for all the place

**Comment by Kavinkumars23** [comment]
used setOpenAccordion((prev) => (prev === index ? null : index)); line directly
changed openAccordion === index ? "group-open" : "" with  &&
validated item.title
